# Generated by Django 3.2.7 on 2021-09-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photoFileName',
            field=models.TextField(blank=True),
        ),
    ]
